ROOT_PATH_DROPBOX = 'C:\\Users\S.Palacio\Dropbox'
LOCAL = ROOT_PATH_DROPBOX + '\\PHD\Trabajo 4\\5Finder 1.0.0'

# PATH NAMES
path_test = '\\resources\\test_data\\'
path_test_db = '\\resources\\test_data\\test'
path_ine = LOCAL + '\\resources\\INE\\'
path_db = LOCAL + '\\data_training'
path_resources = LOCAL + '\\resources'
path_spark_remote = LOCAL + '\\spark-2.3.1-bin-hadoop2.7'
path_spark_local = ROOT_PATH_DROPBOX + '\\Python Dev\spark-2.3.1-bin-hadoop2.7'
# FILE NAMES
file_claim = '\\clientesiniestro_od.csv'
file_country = 'auxiliar\\country_list.csv'

class Parameters:
# VEHICULO USO CODIGO

    """
    110	TURISMO PARTICULAR
    111	TURISMO PARTICULAR MATRICULADO A NOMBRE DE EMPRESA
    113	TURISMO PARTICULAR HISTÃ“RICO
    114	TURISMO PARTICULAR (MICROBUS)
    117	TURISMO PARTICULAR CLÃSICO
    121	TURISMO FUNERARIO
    131	TURISMO SERVICIO PUBLICO SIN TAXIMETRO
    132	TURISMO AMBULANCIA
    133	TURISMO SERVICIO PUBLICO CON TAXIMETRO CONDUCIDO EXCL.POR PROPIET.
    135	TURISMO SERVICIO PUBLICO CON TAXIMETRO CONDUCIDO POR EMPLEADO
    137	TURISMO SERVICIO PUBLICO (MICROBUSES)
    141	TURISMO ALQUILER SIN CONDUCTOR
    142	TURISMO ALQUILER CON CONDUCTOR
    150	TURISMO ESCUELA DE CONDUCTORES
    209	FURGONETA PARTICULAR Y TRANSPORTES PROPIOS MATERIAS PELIGROSAS
    210	FURGONETA PARTICULAR Y TRANSPORTES PROPIOS
    212	FURGONETA PARTICULAR Y TRANSP.PROPIOS AGRICOLAS Y GANADEROS.
    219	FURGONETA AUTOCARAVANA
    220	FURGONETA PARTICULAR Y TRANSPORTES TERCEROS
    228	FURGONETA PARTICULAR Y TRANSPORTES TERCEROS MATERIAS PELIGROSAS
    229	FURGONETA HISTORICA.
    230	FURGONETA CLASICA.
    234	FURGONETA SERVICIO PUBLICO SIN TAXIMETRO
    235	FURGONETA SERVICIO PUBLICO CON TAXIMETRO CONDUCIDO POR EMPLEADO
    236	FURGONETA SERVICIO PUBLICO CON TAXIMETRO CONDUCIDO EXCL. POR PROPIET.
    237	FURGONETA AMBULANCIA
    238	FURGONETA FUNERARIO
    246	FURGONETA ALQUILER CON CONDUCTOR
    250	FURGONETA ESCUELA DE CONDUCTORES
    267	FURGONETA ALQUILER SIN CONDUCTOR
    309	CAMION TRANSPORTES PROPIOS MATERIAS PELIGROSAS
    310	CAMION TRANSPORTES PROPIOS
    320	CAMION TRANSPORTES TERCEROS
    327	CAMION TRANSP.DE ATRACCIONES AMBULANTES (FIESTAS MAYORES Y FERIAS)
    328	CAMION TRANSPORTES TERCEROS MATERIAS PELIGROSAS
    346	CAMION ALQUILER
    350	CAMION ESCUELA DE CONDUCTORES
    410	VEHICULOS INDUSTRIALES SERVICIO PROPIO
    420	VEHICULOS INDUSTRIALES SERVICIO PUBLICO Y/O TERCEROS
    440	VEHICULOS INDUSTRIALES ALQUILER
    450	VEHICULOS INDUSTRIALES ESCUELA DE CONDUCTORES
    510	AUTOCARES SERVICIO PROPIO
    530	AUTOCARES SERVICIO PUBLICO DE VIAJEROS EN LINEA REGULAR
    531	AUTOCARES SERVICIO PUBLICO DE VIAJEROS EN LINEA URBANA
    532	AUTOCARES SERVICIO PUBLICO DE VIAJEROS EN LINEA INTERURBANA
    540	AUTOCARES SERVICIO PUBLICO O DE ALQUILER
    542	AUTOCARES SERV.PUBLICO O ALQUILER, SERV.INTERURBANO Y EXCURSIONES
    550	AUTOCARES ESCUELAS DE CONDUCTORES
    610	VEHICULOS AGRICOLAS TRABAJOS PROPIOS
    611	VEHICULOS AGRICOLAS TRABAJOS PROPIOS AGRICOLAS
    620	VEHICULOS AGRICOLAS TRABAJOS PARA TERCEROS
    621	VEHICULOS AGRICOLAS TRABAJOS PARA TERCEROS, AGRICOLAS
    641	VEHICULOS AGRICOLAS ALQUILER PARA TRABAJOS AGRICOLAS
    680	VEHICULOS AGRICOLAS ESCUELA DE CONDUCTORES
    710	CICLOMOTORES Y MOTOCICLETAS PARTICULAR
    713	CICLOMOTORES Y MOTOCICLETAS PARTICULAR HISTORICO
    717	CICLOMOTORES Y MOTOCICLETAS PARTICULAR (MOTOCICLETA CLASICA)
    730	CICLOMOTORES Y MOTOCICLETAS SERVICIO PUBLICO
    740	CICLOMOTORES Y MOTOCICLETAS ALQUILER
    750	CICLOMOTORES Y MOTOCICLETAS ESCUELA DE CONDUCTORES
    810	TRICICLOS Y MOTOCARROS TRANSPORTES PROPIOS
    820	TRICICLOS Y MOTOCARROS TRANSPORTES A TERCEROS
    909	REMOLQUES Y SEMIREMOLQUES TRANSPORTES PROPIOS MATERIAS PELIGROSAS
    910	REMOLQUES Y SEMIREMOLQUES TRANSPORTES PROPIOS
    920	REMOLQUES Y SEMIREMOLQUES TRANSPORTES PUBLICOS Y/O TERCEROS
    927	REMOLQUES Y SEMIREMOLQUES TRANSP.ATRAC.AMBULANTES (FIESTAS MAYORES Y FERIAS)
    928	REMOLQUES Y SEMIREMOLQUES TRANSP.PUBLICOS Y/O TERCEROS MATERIAS PELIGROSAS
    946	REMOLQUES Y SEMIREMOLQUES ALQUILER
    950	REMOLQUES Y SEMIREMOLQUES ESCUELA DE CONDUCTORES
    960	REMOLQUES Y SEMIREMOLQUES REMOLQUE CARAVANA PARTICULAR

    """

    # BONUS
    """
    55%  BONUS	2
    50%  BONUS	3
    45%  BONUS	4
    40%  BONUS	5
    35%  BONUS	6
    30%  BONUS	7
    25%  BONUS	8
    20%  BONUS	9
    10%  BONUS	11
    0	13
    10%  MALUS	14
    20%  MALUS	15
    30%  MALUS	17
    40%  MALUS	18
    50%  MALUS	19
    70%  MALUS	20
    200%  MALUS	24
    """

    # CULPA
    """
    A Culpa segurado, C Culpa contrario, N Sin culpa
    """

    # IDS
    """    
    C = CIF
    N or R = NIF
    P = Passport
    S or T = Non - identified
    E = CEE Foreing enterprise
    X = Not CEE Foreing enterprise
    """

    # VEHICULO CATEGORIA
    """
    Categoría del Vehículo (Turismo, Resto, Motos)
    """